### PR TITLE
feat(celery task): The ability of backfilling copernicus data

### LINKED ISSUE #4: Make celery catchup data from present until 2000
- Generate a file containing every day between 2022 and 2000.
- Celery will read this file and execute a task every hour until it reaches the end

### PR DESCRIPTION
**Pull request by luabida**
Since Airflow is not available, I've added a new task that reads a file hourly, searching for dates to be uploaded.

Every date with the tag `false` will be used as an argument to the task flow and changed to `true` after read.

fix #4

### CODE REVIEW

**Comment by luabida** [comment]
### Methods used to generate the file:

```
dates = pd.bdate_range(start='1/1/2000', end='11/15/2022', freq='D')[::-1]

for date in dates:
    d = date.date().strftime("%Y-%m-%d")
    line = str(d) + ' False\n'
    file = 'backfill_cope_dates.txt'
    with open(file, 'a', encoding='utf-8') as f:
        f.write(line)
```

**Comment by esloch** [comment]
I suggest using the ports as environment variables, because in production we will have more than one rabbitmq server running.
from:
``` 
...
  rabbitmq:
    image: rabbitmq:3-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
```
to:
``` 
...
    ports:
      - ${RBTMQ_PORT}:${RBTMQ_PORT}

```

**Comment by luabida** [comment]
@esloch rabbitmq is fixed [here](#7), along with the flower addition.

**Review by esloch — APPROVED** [review]
LGTM!

**Pull request merged**
